# Build only for stack 8.0.2 for now
# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

addons:
  apt:
    packages:
    - 
    - mapnik-vector-tile 

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: BUILD=stack ARGS="--resolver lts-8"
    compiler: ": #stack 8.0.2"
    addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}  
  fast_finish: true

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script: stack $ARGS --no-terminal --install-ghc test --haddock
